home:
    path:     /
    defaults: { _controller: KodifyBlogBundle:Posts:index }
authors:
    path:     /authors
    defaults: { _controller: KodifyBlogBundle:Authors:index }
create_post:
    path:     /posts/create
    defaults: { _controller: KodifyBlogBundle:Posts:create }
view_post:
    path:     /posts/{id}
    defaults: { _controller: KodifyBlogBundle:Posts:view }
create_author:
    path:     /authors/create
    defaults: { _controller: KodifyBlogBundle:Authors:create }
add_comment:
    path:     /comment/add/{post_id}
    defaults: { _controller: KodifyBlogBundle:Comment:add }