<?php

namespace Kodify\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends AbstractBaseRepository
{
    public function queryPostsComments($post_id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c,p FROM KodifyBlogBundle:Comment c INNER JOIN c.post p WHERE p.id = :post_id ORDER BY c.createdAt DESC')
            ->setParameter('post_id', $post_id);
    }
}
